name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.8
        run: cargo build --locked
      - name: Run tests
        run: cargo test --locked --verbose

